# Base configs
baseurl: "https://photos.lorderikir.me"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Eric Jiang"
subtitle: "I build software, love travelling and enjoy taking photos"
author: "Eric Jiang"
header:
  title: "Photos"
  subtitle: "by Eric"
footer:
  name: "Hi there, I'm Eric"
  bio: "I build software, love travelling and enjoy taking photos"
  # github: 'Want a website like this for yourself for free? Just <a href="https://github.com/ramswaroop/photography">fork me on github</a> ;)'
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/lorderikir"
  twitter: "https://www.twitter.com/lorderikir"
  instagram: "https://www.instagram.com/lorderikir"
  linkedin: "https://in.linkedin.com/in/ericjiang97"
  github: "https://www.github.com/lorderikir"
